version: '3.8'

services:
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.10
    volumes:
      - ./fluent-bit-playground.conf:/fluent-bit/etc/fluent-bit.conf
      - ./target/wasm32-unknown-unknown/release/fluent_ecs.wasm:/fluent_ecs.wasm